name: linter-check
on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: lint application
        run: poetry run flake8 brain_games
